name: wp-stack
recipe: wordpress
proxy:
  mailhog:
    - mail.wp-stack.lndo.site
config:
  php: '7.2'
  via: apache:2.4
  webroot: web
  database: mysql:5.7
  xdebug: true
services:
  appserver:
    config:
      vhosts: .lando/default-ssl.conf
    run_as_root:
      - a2enmod http2
  composer:
    type: php:7.2
    run:
      - composer update
      - composer install
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
events:
  pre-start:
    - cp .env.lando .env
  post-start:
    - sh scripts/setup.sh
